AWSTemplateFormatVersion: 2010-09-09

Description: Create a SNS Topic

Parameters:  
  SnsTopicName:
    Description: 'A name for the SNS topic'
    Type: String
    
Resources:
  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Ref SnsTopicName
      TopicName: !Ref SnsTopicName
  SnsTopicPolicy: 
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        Version: '2008-10-17'
        Id: __default_policy_ID
        Statement:
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'SNS:GetTopicAttributes'
              - 'SNS:SetTopicAttributes'
              - 'SNS:AddPermission'
              - 'SNS:RemovePermission'
              - 'SNS:DeleteTopic'
              - 'SNS:Subscribe'
              - 'SNS:ListSubscriptionsByTopic'
              - 'SNS:Publish'
              - 'SNS:Receive'
            Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SnsTopicName}'
            Condition:
              StringEquals:
                'AWS:SourceOwner': !Ref AWS::AccountId
          - Sid: __console_sub_0
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 
              - 'SNS:Subscribe'
              - 'SNS:Receive'
            Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SnsTopicName}'
      Topics: 
        - !Ref SnsTopic

Outputs:
  SnsTopicArn:
    Description: Name of newly created SNS Topic
    Value: !Ref SnsTopic