AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This policy will be used as a permission boundary policy
  that will be attached to the non-compliant roles.
Resources:
  QuarantinePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'pb_quarantine_policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'DenyAllExceptIamReadOnlyAndSupport'
            Effect: 'Allow'
            Action:
              - 'iam:List*'
              - 'iam:Get*'
              - 'support:*'
            Resource: '*'
Outputs:
  DenyAllPolicyArn:
    Value: !Ref QuarantinePolicy
