AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
  AdminPolicyArn:
    Type: String
  TeamAdminPermissionBoundaryPolicyArn:
    Type: String
Resources:
  AdminRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - !Ref AdminPolicyArn
      PermissionsBoundary: !Ref TeamAdminPermissionBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::123456789012:root'
            Action:
              - 'sts:AssumeRole'
      RoleName: !Sub '${ApplicationName}-admin-role'
      Policies:
        - PolicyName: AppAdminRole_InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'aws-portal:ViewUsage'
                  - 'aws-portal:ViewBilling'
                  - 'support:*'
Outputs:
  AdminRoleArn:
    Value: !GetAtt AdminRole.Arn
  AdminRoleId:
    Value: !GetAtt AdminRole.RoleId
