AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This is the main stack for creating the job function roles for an application team.
Parameters:
  ApplicationName:
    Type: String
    Default: 'app'
  S3BucketName:
    Type: String
Resources:
  TeamAdminPermissionBoundaryPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/${ApplicationName}-team-admin-permission-boundary.yml"
      Parameters:
        ApplicationName: !Ref ApplicationName
  TeamWidePermissionBoundaryPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/${ApplicationName}-team-wide-permission-boundary.yml"
      Parameters:
        ApplicationName: !Ref ApplicationName
  AdminPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://${S3BucketName}.s3.amazonaws.com/${ApplicationName}-admin-role-permission-policy.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
  AdminRole:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AdminPolicy
      - TeamAdminPermissionBoundaryPolicy
    Properties:
      TemplateURL: https://${S3BucketName}.s3.amazonaws.com/${ApplicationName}-admin-role.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        AdminPolicyArn: !GetAtt AdminPolicy.Outputs.AdminPolicyArn
        TeamAdminPermissionBoundaryPolicyArn: !GetAtt TeamAdminPermissionBoundaryPolicy.Outputs.TeamAdminPermissionBoundaryPolicyArn
  SupportRole:
    Type: AWS::CloudFormation::Stack
    DependsOn: TeamWidePermissionBoundaryPolicy
    Properties:
      TemplateURL: https://${S3BucketName}.s3.amazonaws.com/${ApplicationName}-support-role.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        TeamWidePermissionBoundaryPolicyArn: !GetAtt TeamWidePermissionBoundaryPolicy.Outputs.TeamWidePermissionBoundaryPolicyArn
Outputs:
  TeamAdminPermissionBoundaryPolicyStackRef:
    Value: !Ref TeamAdminPermissionBoundaryPolicy
  TeamWidePermissionBoundaryPolicyStackRef:
    Value: !Ref TeamWidePermissionBoundaryPolicy
  AdminPolicyStackRef:
    Value: !Ref AdminPolicy
  AdminRoleStackRef:
    Value: !Ref AdminRole
  SupportRoleStackRef:
    Value: !Ref SupportRole
