AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
  TeamWidePermissionBoundaryPolicyArn:
    Type: String
Resources:
  SupportRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
      PermissionsBoundary: !Ref TeamWidePermissionBoundaryPolicyArn
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::123456789012:root'
            Action:
              - 'sts:AssumeRole'
      RoleName: !Sub '${ApplicationName}-support-role'
      Policies:
        - PolicyName: AppSupportRole_InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'aws-portal:ViewUsage'
                  - 'aws-portal:ViewBilling'
                  - 'support:*'
Outputs:
  SupportRoleArn:
    Value: !GetAtt SupportRole.Arn
  SupportRoleId:
    Value: !GetAtt SupportRole.RoleId
