AWSTemplateFormatVersion: 2010-09-09

Description: >-
  A bucket holding access logs for a selected region. This bucket
  must be in the same region as the source bucket. The SNS topic
  must also exist in the same region as the source bucket.

Parameters:
  S3BucketName:
    Type: String
    Description: Enter the S3 bucket name

  EnvironmentTag:
    Type: String
    Description: Enter environment

  VersioningEnabled:
    Type: String
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
    Description: Versioning Status

  ExistingS3EventNotificationSnsTopic:
    Type: String

Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
        LogFilePrefix: !Sub "${S3BucketName}/"
      VersioningConfiguration:
        Status: !Ref VersioningEnabled
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectRemoved:*'
            Topic: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ExistingS3EventNotificationSnsTopic}'
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
        - Key: Environment
          Value: !Ref EnvironmentTag

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: "Name of the bucket that stores access logs for all buckets in the selected region"