AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A bucket holding access logs for a selected region. This bucket
  must be in the same region as the source bucket. This template 
  works in us-east-1 region because of the location of the SNS topic.
Parameters:
  S3BucketName:
    Type: String
    Description: Enter the S3 bucket name
  ApplicationTag:
    Type: String
    Description: Enter application name
  ConsumerTag:
    Type: String
    Description: Enter resource owner's email address
  CostcenterTag:
    Type: String
    Description: Enter cost center
  DivisionTag:
    Type: String
    Description: Enter division
  EnvironmentTag:
    Type: String
    Description: Enter environment
  VersioningEnabled:
    Type: String
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
    Description: Versioning Status
  ExistingS3EventNotificationSnsTopic:
    Type: String
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
        LogFilePrefix: !Sub "${S3BucketName}/"
      VersioningConfiguration:
        Status: !Ref VersioningEnabled
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectRemoved:*'
            Topic: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ExistingS3EventNotificationSnsTopic}'
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref S3BucketName, !Ref 'AWS::Region']]
        - Key: Application
          Value: !Ref ApplicationTag
        - Key: Consumer
          Value: !Ref ConsumerTag
        - Key: Costcenter
          Value: !Ref CostcenterTag
        - Key: Division
          Value: !Ref DivisionTag
        - Key: Environment
          Value: !Ref EnvironmentTag
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: "Name of the bucket that stores access logs for all buckets in the selected region"