AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SNS topic that is used to notify about the creation of
  a non-compliant S3 bucket policy
Parameters:
  SnsTopicName:
    Type: String
Resources:
  SnsTopicForConfig:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: 'mytestemail@fake.com'
          Protocol: 'email'
      TopicName: !Ref SnsTopicName
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Id: MyTopicPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: 'DefaultStatement'
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
            - 'SNS:GetTopicAttributes'
            - 'SNS:SetTopicAttributes'
            - 'SNS:AddPermission'
            - 'SNS:RemovePermission'
            - 'SNS:DeleteTopic'
            - 'SNS:Subscribe'
            - 'SNS:ListSubscriptionsByTopic'
            - 'SNS:Publish'
            - 'SNS:Receive'
          Resource: !Ref SnsTopicForConfig
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref 'AWS::AccountId'
        - Sid: 'AllowCloudWatchEventsToPublishSnsTopic'
          Effect: Allow
          Principal:
            Service: 'lambda.amazonaws.com'
          Action: 
            - 'sns:Publish'
          Resource: !Ref SnsTopicForConfig
      Topics: 
        - !Ref SnsTopicForConfig
Outputs:
  SnsTopicName:
    Value: !GetAtt SnsTopicForConfig.TopicName
    Description: 'SNS Topic Name'
  SnsTopicArn:
    Value: !Ref SnsTopicForConfig
    Description: 'SNS Topic ARN'
