AWSTemplateFormatVersion: 2010-09-09

Description: >-
  A policy that will allow users to enable MFA for themselves,
  and block most actions unless they are signed in with MFA.

Resources:
  CloudAdminsGroupPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: String
      ManagedPolicyName: cloud-admins-group-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowListActions
            Effect: Allow
            Action:
              - 'iam:ListUsers'
              - 'iam:ListVirtualMFADevices'
            Resource: '*'
          - Sid: AllowIndividualUserToListOnlyTheirOwnMFA
            Effect: Allow
            Action:
              - 'iam:ListMFADevices'
              - 'iam:ListVirtualMFADevices'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:mfa/*'
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/' , '${aws:username}' ] ]
          - Sid: AllowIndividualUserToManageTheirOwnMFA
            Effect: Allow
            Action:
              - 'iam:CreateVirtualMFADevice'
              - 'iam:DeleteVirtualMFADevice'
              - 'iam:EnableMFADevice'
              - 'iam:ResyncMFADevice'
            Resource:
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:mfa/' , '${aws:username}' ] ]
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/' , '${aws:username}' ] ]
          - Sid: AllowIndividualUserToDeactivateOnlyTheirOwnMFAOnlyWhenUsingMFA
            Effect: Allow
            Action:
              - 'iam:DeactivateMFADevice'
            Resource:
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:mfa/' , '${aws:username}' ] ]
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/' , '${aws:username}' ] ]
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
          - Sid: BlockMostAccessUnlessSignedInWithMFA
            Effect: Deny
            NotAction:
              - 'iam:CreateVirtualMFADevice'
              - 'iam:EnableMFADevice'
              - 'iam:ListMFADevices'
              - 'iam:ListUsers'
              - 'iam:ListVirtualMFADevices'
              - 'iam:ResyncMFADevice'
              - 'iam:ChangePassword'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:mfa/*'
              - !Join [ '', [ !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/' , '${aws:username}' ] ]
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: 'false'